apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: networkingstack
spec:
  compositeTypeRef:
    apiVersion: example.crossplane.io/v1
    kind: NetworkingStack
  mode: Pipeline
  pipeline:
  - step: kro-run
    functionRef:
      name: function-kro
    input:
      apiVersion: kro.fn.crossplane.io/v1alpha1
      kind: ResourceGraph
      status:
        networkingInfo:
          vpcID: ${vpc.status.atProvider.id}
          subnetAZA: ${subnetAZA.status.atProvider.id}
          subnetAZB: ${subnetAZB.status.atProvider.id}
          subnetAZC: ${subnetAZC.status.atProvider.id}
          securityGroup: ${securityGroup.status.atProvider.id}
      resources:
      - id: vpc
        template:
          apiVersion: ec2.aws.upbound.io/v1beta1
          kind: VPC
          metadata: {}
          spec:
            forProvider:
              region: ${schema.spec.region}
              cidrBlock: 192.168.0.0/16
              enableDnsHostnames: false
              enableDnsSupport: true
      - id: subnetAZA
        template:
          apiVersion: ec2.aws.upbound.io/v1beta1
          kind: Subnet
          metadata: {}
          spec:
            forProvider:
              region: ${schema.spec.region}
              availabilityZone: ${schema.spec.region + "a"}
              cidrBlock: 192.168.0.0/18
              vpcId: ${vpc.status.atProvider.id}
      - id: subnetAZB
        template:
          apiVersion: ec2.aws.upbound.io/v1beta1
          kind: Subnet
          metadata: {}
          spec:
            forProvider:
              region: ${schema.spec.region}
              availabilityZone: ${schema.spec.region + "b"}
              cidrBlock: 192.168.64.0/18
              vpcId: ${vpc.status.atProvider.id}
      - id: subnetAZC
        template:
          apiVersion: ec2.aws.upbound.io/v1beta1
          kind: Subnet
          metadata: {}
          spec:
            forProvider:
              region: ${schema.spec.region}
              availabilityZone: ${schema.spec.region + "c"}
              cidrBlock: 192.168.128.0/18
              vpcId: ${vpc.status.atProvider.id}
      - id: securityGroup
        template:
          apiVersion: ec2.aws.upbound.io/v1beta1
          kind: SecurityGroup
          metadata: {}
          spec:
            forProvider:
              name: my-sg-${schema.metadata.name}
              region: ${schema.spec.region}
              description: something something
              vpcId: ${vpc.status.atProvider.id}
  - step: auto-ready
    functionRef:
      name: function-auto-ready
