apiVersion: ec2.aws.upbound.io/v1beta1
kind: VPC
metadata:
  annotations:
    crossplane.io/composition-resource-name: vpc
  generateName: example-stack-
  name: example-stack-random
  labels:
    crossplane.io/composite: example-stack
  ownerReferences:
  - apiVersion: example.crossplane.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: NetworkingStack
    name: example-stack
    uid: ""
spec:
  forProvider:
    cidrBlock: 192.168.0.0/16
    enableDnsHostnames: false
    enableDnsSupport: true
status:
  atProvider:
    id: some-cool-vpc